baseURL = "https://premy.hata6502.com/"
languageCode = "en-us"
title = "premy - A drawing app for anyone. "
theme = "minimal"
googleAnalytics = "UA-106651880-7"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    author = "Tomoyuki Hata"
    description = "A drawing app for anyone. "
    githubUsername = "#hata6502"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://twitter.com/premy_draw"
    name = "fab fa-twitter"
    weight = 1

[[menu.icon]]
    url = "https://helpfeel.com/hata6502/?q=premy"
    name = "fas fa-question"
    weight = 2

[[menu.icon]]
    url = "https://github.com/hata6502/premy"
    name = "fab fa-github"
    weight = 3

[[menu.icon]]
    url = "https://github.com/sponsors/hata6502"
    name = "fas fa-heart"
    weight = 4
